# This file is part of BOINC.
# https://boinc.berkeley.edu
# Copyright (C) 2021 University of California
#
# BOINC is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License
# as published by the Free Software Foundation,
# either version 3 of the License, or (at your option) any later version.
#
# BOINC is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with BOINC.  If not, see <http://www.gnu.org/licenses/>.

codecov:
  require_ci_to_pass: yes
  notify:
    after_n_builds: 4
    wait_for_ci: yes

coverage:
  status:
    project: off
    patch:
      default:
        threshold: 0.01

comment:
  layout: "diff, files"
  behavior: default
  require_changes: yes    # if true: only post the comment if coverage changes
  require_base: no        # [yes :: must have a base report to post]
  require_head: yes       # [yes :: must have a head report to post]
  branches:
    - master
  after_n_builds: 4

flags:
  # filter the folder(s) you wish to measure by that flag
  boinc-autodock-vina:
    paths:
      - boinc-autodock-vina/src/

# don't gather statistics for test and external libraries
ignore:
  - "**/src/unit-tests/*"
