name: Windows
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '0 12 * * 0'

jobs:
  build:
    name: ${{ matrix.app }}-${{ matrix.configuration }}-build
    runs-on: windows-latest
    strategy:
      matrix:
        app: [boinc-autodock-vina]
        configuration: [x64-windows-static, x86-windows-static]
      fail-fast: false
    env:
      VCPKG_BINARY_SOURCES: 'clear;files,${{ github.workspace }}\vcpkgcache\,readwrite'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Download OpenCppCoverage
        uses: suisei-cn/actions-download-file@v1
        if: success()
        id: DownloadOpenCppCoverage
        with:
          url: "https://opencppcoverage.gallerycdn.vsassets.io/extensions/opencppcoverage/opencppcoverageplugin/0.9.7.1/1581265346391/OpenCppCoverage-0.9.7.1.vsix"
          target: ${{ github.workspace }}\temp\

      - name: Unzip OpenCppCoverage
        if: success()
        uses: DuckSoft/extract-7z-action@v1.0
        with:
          pathSource: ${{ github.workspace }}\temp\OpenCppCoverage-0.9.7.1.vsix
          pathTarget: ${{ github.workspace }}\temp\OpenCppCoverage

      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1

      - name: Fix vcpkg
        run: vcpkg.exe integrate remove

      - name: Configure Python
        if: ${{ success() }}
        shell: cmd
        run: |
          pip3 install boto3

      - name: Download vcpkg binary cache
        if: ${{ success() }}
        shell: cmd
        run: |
          python3 deploy\manage_vcpkg_archive_cache.py download ${{ github.workspace }}\vcpkgcache ${{ matrix.configuration }} "vcpkg.cache.boinc-apps.${{ matrix.app }}"

      - name: Build
        if: ${{ success() }}
        run: python3 build.py -nt -ts=ci -t=${{ matrix.configuration }} ${{ matrix.app }}

      - name: Test
        if: ${{ success() }}
        run: python3 build.py -nb -ts=ci -t=${{ matrix.configuration }} ${{ matrix.app }}

      - name: Upload artifacts
        if: ${{ success()}}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.app }}-${{ matrix.configuration }}-${{ github.event.pull_request.head.sha }}
          path: build/${{ matrix.app }}/${{ matrix.configuration }}/Release/*.exe

      - name: Upload coverage report
        if: ${{ success() }}
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          verbose: false

      - name: Upload vcpkg binary cache
        if: ${{ success() }}
        shell: cmd
        env:
          ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
        run: |
          python3 deploy\manage_vcpkg_archive_cache.py upload ${{ github.workspace }}\vcpkgcache ${{ matrix.configuration }} "vcpkg.cache.boinc-apps.${{ matrix.app }}" "%ACCESS_KEY%" "%SECRET_KEY%"
